/**
 * Bot Configuration
 */

import dotenv from 'dotenv';
dotenv.config();

export const CONFIG = {
  // Network
  network: process.env.NETWORK || 'testnet',
  rpcUrl: process.env.RPC_URL || 'https://soroban-testnet.stellar.org',
  horizonUrl: process.env.HORIZON_URL || 'https://horizon-testnet.stellar.org',
  networkPassphrase:
    process.env.NETWORK === 'mainnet'
      ? 'Public Global Stellar Network ; September 2015'
      : 'Test SDF Network ; September 2015',

  // Bot Wallet
  botSecretKey: process.env.BOT_SECRET_KEY || '',

  // Contracts
  soroswapRouter: process.env.SOROSWAP_ROUTER || 'CCMAPXWVZD4USEKDWRYS7DA4Y3D7E2SDMGBFJUCEXTC7VN6CUBGWPFUS',
  soroswapFactory: process.env.SOROSWAP_FACTORY || 'CDJTMBYKNUGINFQALHDMPLZYNGUV42GPN4B7QOYTWHRC4EE5IYJM6AES',
  savexContract: process.env.SAVEX_CONTRACT || 'CD62XQRCEXAEZL4KOGOINLVZSKPTI4VNAHDDCSZZFL3EX3Y4B4PDMKBC',

  // Trading Parameters
  pollIntervalMs: parseInt(process.env.POLL_INTERVAL_MS || '5000'),
  minProfitPercent: parseFloat(process.env.MIN_PROFIT_PERCENT || '0.5'),
  maxTradeAmountXlm: parseFloat(process.env.MAX_TRADE_AMOUNT_XLM || '1000'),
  maxSlippagePercent: parseFloat(process.env.MAX_SLIPPAGE_PERCENT || '2'),
} as const;

// Known pools from discovery
export const KNOWN_POOLS = [
  {
    address: 'CDIEPNPMEYBKZZVXNB2PLJMGFVLWJ32YNU5RIF4DOF7G6DTEZFBJHIDS',
    token0: 'CCSV3Y6QKAPRZCPLCMC5W7OCS5BFPKMYFK5GC25SSSS44U2WA4Y7QRKE', // XTAR
    token1: 'CDWEFYYHMGEZEFC5TBUDXM3IJJ7K7W5BDGE765UIYQEV4JFWDOLSTOEK', // USDC
    name: 'XTAR/USDC',
  },
  {
    address: 'CDT3AHGQC4PYFGMJWBIY2VLZIZ7CBMCKZ7BZMYC55WIVPDPRYWYBHD4I',
    token0: 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC', // XLM
    token1: 'CDWEFYYHMGEZEFC5TBUDXM3IJJ7K7W5BDGE765UIYQEV4JFWDOLSTOEK', // USDC
    name: 'XLM/USDC',
  },
  {
    address: 'CDE3I665APUHQYMATNLEODUPIWTEWXB5NB5IEV6NNNDQ3ZYRJ3SSWZKM',
    token0: 'CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA', // USDC (alt)
    token1: 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC', // XLM
    name: 'USDC/XLM',
  },
  {
    address: 'CCJQDQ3Y3WXJJQIDMAWK77DGDETT5U222OU2ARGYZWYSPDDFXYAJVWSR',
    token0: 'CAUL6I3KR55BAOSOE23VRR5FUFD2EEBWF3DHGWUZN7N3ZGVR4QQU6DQM', // EURC
    token1: 'CDWEFYYHMGEZEFC5TBUDXM3IJJ7K7W5BDGE765UIYQEV4JFWDOLSTOEK', // USDC
    name: 'EURC/USDC',
  },
  {
    address: 'CAP6V6SHXYTT7X3NDMXA3N3T4DPBQOEFHKSHTVMJ4LNGJDBTU7OESN3H',
    token0: 'CCSV3Y6QKAPRZCPLCMC5W7OCS5BFPKMYFK5GC25SSSS44U2WA4Y7QRKE', // XTAR
    token1: 'CD56OXOMAZ55LIKCYVFXH5CP2AKCLYMPMBFRN5XIJVOTWOVY2KFGLZVJ', // AQUA
    name: 'XTAR/AQUA',
  },
];

export const TOKENS = {
  XLM: 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC',
  USDC: 'CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA',
  USDC_ALT: 'CDWEFYYHMGEZEFC5TBUDXM3IJJ7K7W5BDGE765UIYQEV4JFWDOLSTOEK',
  EURC: 'CAUL6I3KR55BAOSOE23VRR5FUFD2EEBWF3DHGWUZN7N3ZGVR4QQU6DQM',
  AQUA: 'CD56OXOMAZ55LIKCYVFXH5CP2AKCLYMPMBFRN5XIJVOTWOVY2KFGLZVJ',
  XTAR: 'CCSV3Y6QKAPRZCPLCMC5W7OCS5BFPKMYFK5GC25SSSS44U2WA4Y7QRKE',
} as const;
